.github/actions/shopware-version/action.yml
Add action to get a suitable shopware version. Will use the same ref as the repo using the action, if it exists. If it does not exist it will use the fallback, which is `trunk` by default.
Example workflow:
```yaml
name: Test
on:
pull_request:
push:
workflow_dispatch:
jobs:
jest:
runs-on: ubuntu-latest
steps:
- uses: shopware/github-actions/.github/actions/shopware-version@add-shopware-version-action
with:
fallback: "6.5.x"
id: version
- name: Setup Shopware
uses: shopware/setup-shopware@main
with:
shopware-version: ${{ steps.version.outputs.shopware-version }}
- name: Print version
shell: bash
run: bin/console --version
```
=> feat: add shopware-version action

.github/workflows/admin-eslint.yml
some plugins require the admin deps to be installed for type information
=> fix: install admin deps in eslint workflow

setup-extension/action.yml
Currently we always checkout the default branch in our dependencies. Some of our workflows need to checkout a different branch of a dependency.
=> feat: allow branch in dependencies

setup-extension/action.yml
We should be able to pass an APP_ENV to setup-shopware
=> feat: Add additional inputs to setup-extension

setup-extension/action.yml
As we are referencing some scripts from platform in some composer scripts in plugins, we need to be able to keep the composer tools.
=> feat: add keep-composer-tools input to setup-extension

setup-extension/action.yml
Currently we are cloning with the `GITHUB_TOKEN` that was set by the last `actions/checkout` action.
A dependency can also be private and need to be cloned with a different token.
With this change we can set the optional "token" in the dependency and then we will use it to clone the dependency with that token.
Example:
```
- uses: shopware/github-actions/setup-extension@feat/add-token-to-dependencies
with:
extensionName: ${{ github.event.repository.name }}
dependencies: |
[
{
"name":"MyExtension",
"repo": "https://github.com/user/MyExtension.git",
"token": "${{ secret.TOKEN }}"
}
]
```
=> feat: add token to dependencies in setup-extension

.github/workflows/admin-jest.yml, .github/workflows/phpstan.yml, .github/workflows/phpunit.yml, phpunit/action.yml
The `phpunit` action also installed shopware. The action should only do things related to its name.
And if we are using a different branch than trunk as platform branch the reusable workflows will fail on the composer steps. We should set the `COMPOSER_ROOT_VERSION` in the workflows.
=> fix: phpunit action should only do phpunit things and set COMPOSER_ROOT_VERSION for reusable Workflows

.github/workflows/admin-jest.yml, .github/workflows/phpstan.yml, .github/workflows/phpunit.yml, setup-extension/action.yml
Remove the `COMPOSER_ROOT_VERSION` from the actions of this repo as it is now set in `setup-extension`.
https://github.com/shopware/setup-shopware/pull/7
=> fix: remove COMPOSER_ROOT_VERSION and set it in setup-shopware

phpstan/action.yml
On the k8s self-hosted runners the github.workspace variable gets resolved wrong. The GITHUB_WORKSPACE environment variables contains the correct resolved path on both runner types, official and self-hosted.
=> fix: use GITHUB_WORKSPACE instead of github.workspace

setup-extension/action.yml
I forgot to add the `-a|--activate` flag in my recent PR #50
=> fix: activate app after installing

build-zip/action.yml, store-release/action.yml
We need to do some preparation before using the shopware-cli. Namely, we want to template the manifest.xml and any hooks defined for the shopware-cli will fail because the manifest.xml won't be found initially and the repo won't be identified as app.
=> feat: Allow skip of recheckout

.github/workflows/build-zip.yml
This pull request includes a change to the GitHub Actions workflow configuration file to update the action used for installing the Shopware CLI.
* [`.github/workflows/build-zip.yml`](diffhunk://#diff-139f590057357be1f0820cc0a36a113091625d66d7424ca6b7cf4118d72b693cL21-R21): Updated the `Install shopware-cli` step to use the `shopware/shopware-cli-action@v1` action instead of the `FriendsOfShopware/shopware-cli-action@v1` action.
=> Update actions to reflect ownership change of shopware-cli-action

setup-extension/action.yml, shopware-version/action.yml
Did not work for some reason
Reverts shopware/github-actions#57
=> revert: feat: use fallbacks on empty version strings

.github/workflows/test.yml, setup-extension/action.yml, shopware-version/action.yml
Second try
Works with single quotes... The parser does not seem to like nested double quotes
=> feat: use fallbacks on empty version strings (2)

.github/workflows/build-zip.yml, .github/workflows/store-release.yml
In order to e.g. apply rules to release jobs, I propose adding the possibility to define an environment. An empty environment is disregarded by GitHub, so this change won't influence existing workflows.
=> chore(ci): add input to allow specifying an environment

downstream/action.yml, downstream/wait.bash
Currently value is 10 seconds, so we should decrease the api requests by a factor of 12
=> feat: add input poll_interval in downstreams with default 2m

shopware-version/shopware-version.bash
For PRs that target 6.6.x we need to use the baseRefName from the PR to find the correct branch in the merge queue
=> fix: use base ref from PR if matching branch does not exist

store-release/action.yml
The path to the build-zip action is missing the "github-actions" repo name
=> fix: fix build-zip action path in store-release action

README.md
This pull request includes several updates to the `README.md` file to improve clarity and accuracy in the documentation for reusable GitHub Actions and Workflows for Shopware extensions. The most important changes are:
Documentation improvements:
* Corrected the capitalization of "extensions" in the title to maintain consistency.
* Clarified the description of the `phpstan` job to specify that it installs Shopware 6, PHPStan, and the extension before running PHPStan.
* Added instructions for creating a `phpstan.neon.dist` file required for the PHPStan check, including specifying the parameters and paths.
* Updated the `Build Zip` section to use consistent capitalization for "extension zip" and "shopware-cli".
* Updated the `Store Upload` section to use consistent capitalization and …
=> Update README.md with phpstan minimum file

downstream/action.yml
In [this downstream pipeline](https://github.com/shopware/shopware/actions/runs/14376060221/job/40308655221?pr=7890) we're using the upstream data generated by the downstream action to determine the shopware version:
```
UPSTREAM_DATA: {
"upstream": {
"id": "14376060221",
"ref": "refs/heads/6.6.x",
"repo": "shopware/shopware",
"github-token": "***",
"url": "https://github.com/shopware/shopware/actions/runs/14376060221"
},
"env": "NIGHTLY="
}
WORKFLOW: Downstream
REPO: shopware/SwagCommercial
REF: next-40170/stop-applying-prefix-for-synonyms-6.6.x
```
Since the source event was a pull_request event, we used the _base_ ref instead of the pull requests _head_ ref, resulting in a failing pipeline since the matching branch wasn't checked out.
I'd propose to use the `head_ref` (only valid and …
=> fix: use `head_ref` in order not to fall back to the PR target branch

versions/action.yml
Because of the new major 6.7 we change now the LTS version to 6.6
=> Change to new major and LTS version in action.yml

build-zip/action.yml, store-release/action.yml
Needed for manipulation before zipping / releasing.
See shopware/braintree-app#271 as example.
=> feat: showpare-cli disable git

shopware-version/shopware-version.bash
BASE_REF was not properly set for merge queue workflow runs
=> fix: BASE_REF detection in merge queue
